#global symbols
#Tue Aug 29 11:02:33 CEST 2023
Transaction.DataStableTimeout=3000
Transaction.DatastableThreshold=2000
tess.db2.username=CONVERTIGO
tess.db2.password=CON123GO
tess.db2.adresse=rentaldev.loxgroup.com
tess.as400.adresse=rentaldev.loxgroup.com
rentalman.db2.username=CONVERTIGO
rentalman.db2.password=CON123GO
rentalman.db2.adresse=rentaldev.loxgroup.com
rentalman.as400.adresse=RENTALDEV.LOXAM.LOC
pwd=
POOL=CNV<POOL:0-9999/4> 
loxshop.smtpuser=appli.loxshop
loxshop.smtpserver=mx2.loxam.loc
loxshop.smtpsenderemail=Loxam <no-reply@loxam.fr>
loxshop.smtpport=25
loxshop.smtppassword=yAlbgfCSbCc4p50VDUVc
loxRental.PROS.username=wsuser
loxRental.PROS.password=ajfi578!fsf85n7l
LoxRental.pollingFrequency=60000
loxRental.email.destinataire=
loxRental.customThreshold=2000
librairie=WSTRAIN
keyring.login.key=123456
keyring.database.adress=localhost
keyring.ciphering.key=azertyui
id=
host_port=
host_name=
codeEcriture=
